name: mira_fashon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  dio: ^5.9.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  image_picker: ^1.1.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  firebase_auth: ^6.1.4
  google_fonts: ^6.2.1
  lottie: ^3.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/