// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsDLrYDGzoGgu8e9daEI0Jx5zQ1kZcWBc',
    appId: '1:52675104570:web:925dad081b713abd0c8a03',
    messagingSenderId: '52675104570',
    projectId: 'auth-flutter-34cf7',
    authDomain: 'auth-flutter-34cf7.firebaseapp.com',
    storageBucket: 'auth-flutter-34cf7.firebasestorage.app',
    measurementId: 'G-E2GGWC3NVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHPG1rAxHcVLrdheNAijW4in_mQ7i-Mk',
    appId: '1:52675104570:android:3b6a2d2fa99d65a70c8a03',
    messagingSenderId: '52675104570',
    projectId: 'auth-flutter-34cf7',
    storageBucket: 'auth-flutter-34cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsUlbe4tE4KLhbBC8sY7Rec16FGzSr_gc',
    appId: '1:52675104570:ios:950bd71f9295ae110c8a03',
    messagingSenderId: '52675104570',
    projectId: 'auth-flutter-34cf7',
    storageBucket: 'auth-flutter-34cf7.firebasestorage.app',
    iosBundleId: 'com.example.miraFashon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsUlbe4tE4KLhbBC8sY7Rec16FGzSr_gc',
    appId: '1:52675104570:ios:950bd71f9295ae110c8a03',
    messagingSenderId: '52675104570',
    projectId: 'auth-flutter-34cf7',
    storageBucket: 'auth-flutter-34cf7.firebasestorage.app',
    iosBundleId: 'com.example.miraFashon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsDLrYDGzoGgu8e9daEI0Jx5zQ1kZcWBc',
    appId: '1:52675104570:web:b610ca7477e7f9530c8a03',
    messagingSenderId: '52675104570',
    projectId: 'auth-flutter-34cf7',
    authDomain: 'auth-flutter-34cf7.firebaseapp.com',
    storageBucket: 'auth-flutter-34cf7.firebasestorage.app',
    measurementId: 'G-QS080FL19W',
  );
}
